import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import RootLayout, { metadata } from "./layout";

describe("RootLayout Component", () => {
	/**
	 * main html tag in next app us rendered at server level,
	 * which is not possible to test in jest & react testing library
	 */

	// test("should render the html and body elements with correct attributes", () => {
	// 	render(
	// 		<RootLayout>
	// 			<p>Test Content</p>
	// 		</RootLayout>
	// 	);

	// 	// Check if the html element has the correct lang attribute
	// 	const htmlElement = document.querySelector("html");
	// 	expect(htmlElement).toHaveAttribute("lang", "en");

	// 	// Check if the body element has the correct class names for fonts and styles
	// 	const bodyElement = document.querySelector("body");
	// 	expect(bodyElement).toHaveClass("antialiased");
	// 	expect(bodyElement).toHaveClass("--font-geist-sans");
	// 	expect(bodyElement).toHaveClass("--font-geist-mono");
	// });

	test("should render children correctly", () => {
		render(
			<RootLayout>
				<p>Test Content</p>
			</RootLayout>
		);

		// Check if the children content is rendered correctly inside the body
		const childrenContent = screen.getByText("Test Content");
		expect(childrenContent).toBeInTheDocument();
	});

	test("metadata object should be defined correctly", () => {
		// Verify the metadata values are correct
		expect(metadata).toEqual({
			title: "Create Next App",
			description: "Generated by create next app",
		});
	});
});
